import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center">Hello Tailwind!</div>
    </>
  );
};

export default Home;
