import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="container h-full mx-auto px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="pt-6 flex justify-center">Hello Tailwind!</div>
    </div>
  );
};

export default Home;
