import Head from "next/head";

const introduction = () => {
  return (
    <>
      <Head>
        <title>Introduction</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center">Introduction</div>
    </>
  );
};

export default introduction;
